"""durable email notifications

Revision ID: 0004_notifications
Revises: 0003_checkpoint_stage
Create Date: 2026-09-06 15:46:50.589416

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_notifications"
down_revision: str | Sequence[str] | None = "0003_checkpoint_stage"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_accounts",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_lock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_subscribers",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("alerts", sa.Boolean(), nullable=False),
        sa.Column("recap", sa.Boolean(), nullable=False),
        sa.Column("job_types", sa.JSON(), nullable=False),
        sa.Column("seasons", sa.JSON(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("opted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_recap", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("sender", sa.String(length=320), nullable=True),
        sa.Column("key_ciphertext", sa.Text(), nullable=True),
        sa.Column("webhook_ciphertext", sa.Text(), nullable=True),
        sa.Column("webhook_id", sa.String(length=64), nullable=False),
        sa.Column("connection_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("suppressed", sa.Boolean(), nullable=False),
        sa.Column("unsubscribe_token", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("unsubscribe_token"),
        sa.UniqueConstraint("webhook_id"),
    )
    op.create_table(
        "notification_webhooks",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("subscriber_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("job_ids", sa.JSON(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "due_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_attempt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("account", sa.String(length=128), nullable=True),
        sa.Column("connection_version", sa.String(length=64), nullable=True),
        sa.Column("provider_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["notification_subscribers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        op.f("ix_notification_deliveries_account"),
        "notification_deliveries",
        ["account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_provider_id"),
        "notification_deliveries",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_status"),
        "notification_deliveries",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_subscriber_id"),
        "notification_deliveries",
        ["subscriber_id"],
        unique=False,
    )
    op.create_table(
        "notification_events",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_postings.id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_notification_events_processed"), "notification_events", ["processed"], unique=False
    )
    op.create_table(
        "notification_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscriber_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_postings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["notification_subscribers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subscriber_id", "job_id"),
    )
    op.create_index(
        op.f("ix_notification_matches_subscriber_id"),
        "notification_matches",
        ["subscriber_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_matches_subscriber_id"), table_name="notification_matches")
    op.drop_table("notification_matches")
    op.drop_index(op.f("ix_notification_events_processed"), table_name="notification_events")
    op.drop_table("notification_events")
    op.drop_index(
        op.f("ix_notification_deliveries_subscriber_id"), table_name="notification_deliveries"
    )
    op.drop_index(op.f("ix_notification_deliveries_status"), table_name="notification_deliveries")
    op.drop_index(
        op.f("ix_notification_deliveries_provider_id"), table_name="notification_deliveries"
    )
    op.drop_index(op.f("ix_notification_deliveries_account"), table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("notification_webhooks")
    op.drop_table("notification_subscribers")
    op.drop_table("notification_lock")
    op.drop_table("notification_accounts")
    # ### end Alembic commands ###
